;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        markdown-outdent-or-delete
        shm/backward-kill-word
        shm/del
        shm/space
        sp-backward-delete-char
        sp-backward-kill-word
        sp-delete-char
        sp-kill-region
        sp-kill-word
        sp-remove-active-pair-overlay
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        term-send-raw
        ))
